#!/usr/bin/env ansible-playbook
---

- hosts: all
  become: true

  vars_files:
    - defaults/main.yml
    - defaults/user.yml

  tasks:
    # could copy and source .env here

    - name: include main tasks
      include: tasks/main.yml

    - name: restart php-fpm on ubuntu
      service: name=php7.0-fpm state=restarted
      when: ansible_distribution|lower == "ubuntu"

    - name: check process
      shell: ps -A | grep php-fpm
      register: php_process

    - name: print process
      debug:
        msg: "{{ php_process.stdout_lines }}"

  handlers:
    - include: handlers/main.yml

# vim:ft=ansible :
