#!/usr/bin/env ansible-playbook
## vim:ft=ansible :

---

# Ubuntu.
- stat: path=/etc/php/7.0/fpm/php.ini
  register: phpfpm_ubuntu

- include: php-fpm-ubuntu.yml
  when: phpfpm_ubuntu.stat.exists

- stat: path=/etc/php/7.0/cli/php.ini
  register: phpcli_ubuntu

- include: php-cli-ubuntu.yml
  when: phpcli_ubuntu.stat.exists

  # Create web directories
- name: Create web directories
  become: true
  shell: mkdir -p /var/www/vhosts/{{ http_domain }}/{{ webroot }} && chmod -R 777 /var/www/vhosts/{{ http_domain }}
  when: ansible_distribution|lower == "ubuntu"

# Copy the Configuration files.
- name: Copy NGINX Config file
  become: true
  template: src=configs/vhost.conf dest=/etc/nginx/sites-enabled/{{ http_domain }}.conf
  notify:
    - restart nginx

# Check to see if a file exists in sql/dump.sql
- name: Check if sql dump exists
  local_action: stat path=sql/dump.sql
  register: sql

# Check to see if a file exists in sql/dump.sql.gz
- name: Check if gzipped sql dump exists
  local_action: stat path=sql/dump.sql.gz
  register: sqlgz

# Import the dump if it exists above
- name: Copy SQL dump if it exists
  become: true
  copy: src=sql/dump.sql dest=/tmp
  when: sql.stat.exists

# Create the database
# TODO fix (not working)
#- name: Create SQL database
#  become: true
#  sql_db: name={{ db_name }} state=present
#
#- name: Import SQL dump if it exists
#  sql_db: name={{ db_name }} state=import target=/tmp/dump.sql
#  when: sql.stat.exists

# Import the gz dump if it exists above
- name: Import GZ SQL dump if it exists
  become: true
  copy: src=sql/dump.sql.gz dest=/tmp
  when: sqlgz.stat.exists

# TODO fix (not working)
#- name: Import GZ SQL dump if it exists
#  sql_db: name={{ db_name }} state=import target=/tmp/dump.sql.gz
#  when: sqlgz.stat.exists

# Install Composer
- name: Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755

# Install CakePHP / Git Repo
- name: Remove Directories
  shell: rm -rf /var/www/vhosts/{{ http_domain }}/app