#!/usr/bin/env ansible-playbook
# vim:ft=ansible :

---

# before install.
- name: Install requires packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - python-apt

- name: Add third-party repository for Ubuntu (PHP)
  become: true
  apt_repository: repo={{ ubuntu_php7_ppa_repo }}
  when: ansible_distribution|lower == "ubuntu"

# MySQL 5.6 for Travis problems
- name: Add old repository for MySQL 5.6 to fix travis errors
  become: true
  apt_repository: repo='deb http://archive.ubuntu.com/ubuntu trusty universe' state=present
  when: ansible_distribution|lower == "ubuntu"

# Update apt cache.
- name: Update apt cache
  become: true
  apt: update_cache=true

# Install PHP7 packages.
- name: Install PHP Packages
  become: true
  apt: name={{ item }} state=latest autoremove=yes
  with_nested: "{{ apt_php_packages }}"
  when: apt_php_packages is defined
  notify:
    - restart php7-fpm

# Install Other packages.
- name: Install Other Packages
  become: true
  apt: name={{ item }} state=latest
  with_nested: "{{ apt_other_packages }}"
  when: apt_other_packages is defined