---

- name: restart php7-fpm
  service: name=php7.1-fpm enabled=yes state=restarted

- name: restart nginx
  service: name=nginx enabled=yes state=restarted

- name: restart postgres
  service: name=postgres enabled=yes state=started

- name: source env
  become: true
  shell: source /.env