---

- name: restart php7-fpm
  service: name=php7.0-fpm enabled=yes state=restarted

- name: restart sphinxsearch
  service: name=sphinxsearch enabled=yes state=restarted

- name: restart nginx
  service: name=nginx enabled=yes state=restarted

- name: restart mysql
  service: name=mysql enabled=yes state=started 

- name: reindex sphinxsearch
  shell: indexer --all --rotate

- name: source env
  become: true
  shell: source /.env